/*
 *
 *
 *   DeviceCommand.java
 *
 *   Copyright (C) 2018 DataArt
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 *
 */

/*
 * Device Hive REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.3.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.devicehive.rest.model;

import com.github.devicehive.rest.adapters.NullJsonAdapter;
import com.google.gson.JsonObject;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;

import org.joda.time.DateTime;

/**
 * DeviceCommand
 */

public class DeviceCommand implements Comparable<DeviceCommand> {
    @SerializedName("id")
    private Long id = null;

    @SerializedName("command")
    private String command = null;

    @SerializedName("timestamp")
    private DateTime timestamp = null;

    @SerializedName("userId")
    private Long userId = null;

    @SerializedName("deviceId")
    private String deviceId = null;

    @SerializedName("networkId")
    private Long networkId = null;
    @JsonAdapter(value = NullJsonAdapter.class)
    @SerializedName("parameters")
    private JsonObject parameters = new JsonObject();

    @SerializedName("lifetime")
    private Integer lifetime = null;

    @SerializedName("status")
    private String status = null;

    @JsonAdapter(value = NullJsonAdapter.class)
    @SerializedName("result")
    private JsonObject result = new JsonObject();

    @SerializedName("isUpdated")
    private Boolean isUpdated = false;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCommand() {
        return command;
    }

    public void setCommand(String command) {
        this.command = command;
    }

    public DateTime getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(DateTime timestamp) {
        this.timestamp = timestamp;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    public Long getNetworkId() {
        return networkId;
    }

    public void setNetworkId(Long networkId) {
        this.networkId = networkId;
    }

    public JsonObject getParameters() {
        return parameters;
    }

    public void setParameters(JsonObject parameters) {
        if (parameters != null) this.parameters = parameters;
    }

    public Integer getLifetime() {
        return lifetime;
    }

    public void setLifetime(Integer lifetime) {
        this.lifetime = lifetime;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public JsonObject getResult() {
        return result;
    }

    public void setResult(JsonObject result) {
        if (result != null) this.result = result;
    }

    public Boolean getUpdated() {
        return isUpdated;
    }

    public void setUpdated(Boolean updated) {
        isUpdated = updated;
    }

    @Override
    public String toString() {
        return "{\n\"DeviceCommand\":{\n"
                + "\"id\":\"" + id + "\""
                + ",\n \"command\":\"" + command + "\""
                + ",\n \"timestamp\":" + timestamp
                + ",\n \"userId\":\"" + userId + "\""
                + ",\n \"deviceId\":\"" + deviceId + "\""
                + ",\n \"networkId\":\"" + networkId + "\""
                + ",\n \"parameters\":" + parameters
                + ",\n \"lifetime\":\"" + lifetime + "\""
                + ",\n \"status\":\"" + status + "\""
                + ",\n \"result\":" + result
                + ",\n \"isUpdated\":\"" + isUpdated + "\""
                + "}\n}";
    }

    @Override
    public int compareTo(DeviceCommand deviceCommand) {
        return getTimestamp().compareTo(deviceCommand.getTimestamp());
    }

}

