/*
 * Device Hive REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.3.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.devicehive.rest.model;

import com.google.gson.annotations.SerializedName;
import lombok.Data;
import org.joda.time.DateTime;

/**
 * ApiInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-20T15:03:42.016+03:00")
@Data
public class ApiInfo {
    @SerializedName("apiVersion")
    private String apiVersion = null;

    @SerializedName("serverTimestamp")
    private DateTime serverTimestamp = null;

    @SerializedName("webSocketServerUrl")
    private String webSocketServerUrl = null;

    public ApiInfo apiVersion(String apiVersion) {
        this.apiVersion = apiVersion;
        return this;
    }

}

