/*
 * Device Hive REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.3.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.devicehive.rest.model;

import com.google.gson.annotations.SerializedName;
import lombok.Data;

/**
 * JwtToken
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-20T15:03:42.016+03:00")
@Data
public class JwtToken {
  @SerializedName("accessToken")
  private String accessToken = null;

  @SerializedName("refreshToken")
  private String refreshToken = null;

  public JwtToken accessToken(String accessToken) {
    this.accessToken = accessToken;
    return this;
  }

  @Override
  public String toString() {
    return "{\n\"JwtToken\":{\n"
            + "\"accessToken\":\"" + accessToken + "\""
            + ",\n \"refreshToken\":\"" + refreshToken + "\""
            + "}\n}";
  }
}

