/*
 * Device Hive REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.3.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.devicehive.rest.model;

import com.google.gson.annotations.SerializedName;
import lombok.Data;
import org.joda.time.DateTime;

import java.util.List;

/**
 * UserWithNetwork
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-20T15:03:42.016+03:00")
@Data
public class UserWithNetwork {
    @SerializedName("id")
    private Long id = null;

    @SerializedName("login")
    private String login = null;


    @SerializedName("role")
    private User.RoleEnum role = null;

    @SerializedName("status")
    private User.StatusEnum status = null;

    @SerializedName("lastLogin")
    private DateTime lastLogin = null;

    @SerializedName("data")
    private JsonStringWrapper data = null;

    @SerializedName("introReviewed")
    private Boolean introReviewed = false;

    @SerializedName("networks")
    private List<NetworkVO> networks = null;

    public UserWithNetwork id(Long id) {
        this.id = id;
        return this;
    }
}

