/**
 * Device Hive REST API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.devicehive.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * ApiConfigVO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-09T14:31:42.381+02:00")
public class ApiConfigVO   {
  @SerializedName("providerConfigs")
  private List<IdentityProviderConfig> providerConfigs = new ArrayList<IdentityProviderConfig>();

  @SerializedName("sessionTimeout")
  private Long sessionTimeout = null;

  public ApiConfigVO providerConfigs(List<IdentityProviderConfig> providerConfigs) {
    this.providerConfigs = providerConfigs;
    return this;
  }

  public ApiConfigVO addProviderConfigsItem(IdentityProviderConfig providerConfigsItem) {
    this.providerConfigs.add(providerConfigsItem);
    return this;
  }

   /**
   * Get providerConfigs
   * @return providerConfigs
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<IdentityProviderConfig> getProviderConfigs() {
    return providerConfigs;
  }

  public void setProviderConfigs(List<IdentityProviderConfig> providerConfigs) {
    this.providerConfigs = providerConfigs;
  }

  public ApiConfigVO sessionTimeout(Long sessionTimeout) {
    this.sessionTimeout = sessionTimeout;
    return this;
  }

   /**
   * Get sessionTimeout
   * @return sessionTimeout
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSessionTimeout() {
    return sessionTimeout;
  }

  public void setSessionTimeout(Long sessionTimeout) {
    this.sessionTimeout = sessionTimeout;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiConfigVO apiConfigVO = (ApiConfigVO) o;
    return Objects.equals(this.providerConfigs, apiConfigVO.providerConfigs) &&
        Objects.equals(this.sessionTimeout, apiConfigVO.sessionTimeout);
  }

  @Override
  public int hashCode() {
    return Objects.hash(providerConfigs, sessionTimeout);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiConfigVO {\n");
    
    sb.append("    providerConfigs: ").append(toIndentedString(providerConfigs)).append("\n");
    sb.append("    sessionTimeout: ").append(toIndentedString(sessionTimeout)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

