/**
 * Device Hive REST API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.devicehive.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;
import org.joda.time.DateTime;


/**
 * ApiInfoVO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-09T14:31:42.381+02:00")
public class ApiInfoVO   {
  @SerializedName("apiVersion")
  private String apiVersion = null;

  @SerializedName("serverTimestamp")
  private DateTime serverTimestamp = null;

  @SerializedName("webSocketServerUrl")
  private String webSocketServerUrl = null;

  @SerializedName("restServerUrl")
  private String restServerUrl = null;

  public ApiInfoVO apiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * Get apiVersion
   * @return apiVersion
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public ApiInfoVO serverTimestamp(DateTime serverTimestamp) {
    this.serverTimestamp = serverTimestamp;
    return this;
  }

   /**
   * Get serverTimestamp
   * @return serverTimestamp
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getServerTimestamp() {
    return serverTimestamp;
  }

  public void setServerTimestamp(DateTime serverTimestamp) {
    this.serverTimestamp = serverTimestamp;
  }

  public ApiInfoVO webSocketServerUrl(String webSocketServerUrl) {
    this.webSocketServerUrl = webSocketServerUrl;
    return this;
  }

   /**
   * Get webSocketServerUrl
   * @return webSocketServerUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getWebSocketServerUrl() {
    return webSocketServerUrl;
  }

  public void setWebSocketServerUrl(String webSocketServerUrl) {
    this.webSocketServerUrl = webSocketServerUrl;
  }

  public ApiInfoVO restServerUrl(String restServerUrl) {
    this.restServerUrl = restServerUrl;
    return this;
  }

   /**
   * Get restServerUrl
   * @return restServerUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRestServerUrl() {
    return restServerUrl;
  }

  public void setRestServerUrl(String restServerUrl) {
    this.restServerUrl = restServerUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiInfoVO apiInfoVO = (ApiInfoVO) o;
    return Objects.equals(this.apiVersion, apiInfoVO.apiVersion) &&
        Objects.equals(this.serverTimestamp, apiInfoVO.serverTimestamp) &&
        Objects.equals(this.webSocketServerUrl, apiInfoVO.webSocketServerUrl) &&
        Objects.equals(this.restServerUrl, apiInfoVO.restServerUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiVersion, serverTimestamp, webSocketServerUrl, restServerUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiInfoVO {\n");
    
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    serverTimestamp: ").append(toIndentedString(serverTimestamp)).append("\n");
    sb.append("    webSocketServerUrl: ").append(toIndentedString(webSocketServerUrl)).append("\n");
    sb.append("    restServerUrl: ").append(toIndentedString(restServerUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

