/**
 * Device Hive REST API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 2.1.1-SNAPSHOT
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.devicehive.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;


/**
 * DeviceVO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-09T14:31:42.381+02:00")
public class DeviceVO {
    @SerializedName("id")
    private String id = null;

    @SerializedName("guid")
    private String guid = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("status")
    private String status = null;

    @SerializedName("data")
    private JsonStringWrapper data = null;

    @SerializedName("network")
    private NetworkVO network = null;

    @SerializedName("deviceClass")
    private DeviceClassVO deviceClass = null;

    @SerializedName("isBlocked")
    private Boolean isBlocked = false;

    public DeviceVO id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * @return id
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public DeviceVO guid(String guid) {
        this.guid = guid;
        return this;
    }

    /**
     * Get guid
     * @return guid
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getGuid() {
        return guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public DeviceVO name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * @return name
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public DeviceVO status(String status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     * @return status
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public DeviceVO data(JsonStringWrapper data) {
        this.data = data;
        return this;
    }

    /**
     * Get data
     * @return data
     **/
    @ApiModelProperty(example = "null", value = "")
    public JsonStringWrapper getData() {
        return data;
    }

    public void setData(JsonStringWrapper data) {
        this.data = data;
    }

    public DeviceVO network(NetworkVO network) {
        this.network = network;
        return this;
    }

    /**
     * Get network
     * @return network
     **/
    @ApiModelProperty(example = "null", value = "")
    public NetworkVO getNetwork() {
        return network;
    }

    public void setNetwork(NetworkVO network) {
        this.network = network;
    }

    public DeviceVO deviceClass(DeviceClassVO deviceClass) {
        this.deviceClass = deviceClass;
        return this;
    }

    /**
     * Get deviceClass
     * @return deviceClass
     **/
    @ApiModelProperty(example = "null", value = "")
    public DeviceClassVO getDeviceClass() {
        return deviceClass;
    }

    public void setDeviceClass(DeviceClassVO deviceClass) {
        this.deviceClass = deviceClass;
    }

    public DeviceVO isBlocked(Boolean isBlocked) {
        this.isBlocked = isBlocked;
        return this;
    }

    /**
     * Get isBlocked
     * @return isBlocked
     **/
    @ApiModelProperty(example = "null", value = "")
    public Boolean getIsBlocked() {
        return isBlocked;
    }

    public void setIsBlocked(Boolean isBlocked) {
        this.isBlocked = isBlocked;
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DeviceVO {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    data: ").append(toIndentedString(data)).append("\n");
        sb.append("    network: ").append(toIndentedString(network)).append("\n");
        sb.append("    deviceClass: ").append(toIndentedString(deviceClass)).append("\n");
        sb.append("    isBlocked: ").append(toIndentedString(isBlocked)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

