/**
 * Device Hive REST API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.devicehive.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;


/**
 * DeviceClassVO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-09T14:31:42.381+02:00")
public class DeviceClassVO   {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("isPermanent")
  private Boolean isPermanent = false;

  @SerializedName("offlineTimeout")
  private Integer offlineTimeout = null;

//  @SerializedName("data")
  private transient JsonStringWrapper data = null;

  @SerializedName("entityVersion")
  private Long entityVersion = null;

  public DeviceClassVO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public DeviceClassVO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DeviceClassVO isPermanent(Boolean isPermanent) {
    this.isPermanent = isPermanent;
    return this;
  }

   /**
   * Get isPermanent
   * @return isPermanent
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsPermanent() {
    return isPermanent;
  }

  public void setIsPermanent(Boolean isPermanent) {
    this.isPermanent = isPermanent;
  }

  public DeviceClassVO offlineTimeout(Integer offlineTimeout) {
    this.offlineTimeout = offlineTimeout;
    return this;
  }

   /**
   * Get offlineTimeout
   * @return offlineTimeout
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getOfflineTimeout() {
    return offlineTimeout;
  }

  public void setOfflineTimeout(Integer offlineTimeout) {
    this.offlineTimeout = offlineTimeout;
  }

  public DeviceClassVO data(JsonStringWrapper data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(example = "null", value = "")
  public JsonStringWrapper getData() {
    return data;
  }

  public void setData(JsonStringWrapper data) {
    this.data = data;
  }

  public DeviceClassVO entityVersion(Long entityVersion) {
    this.entityVersion = entityVersion;
    return this;
  }

   /**
   * Get entityVersion
   * @return entityVersion
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getEntityVersion() {
    return entityVersion;
  }

  public void setEntityVersion(Long entityVersion) {
    this.entityVersion = entityVersion;
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceClassVO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    isPermanent: ").append(toIndentedString(isPermanent)).append("\n");
    sb.append("    offlineTimeout: ").append(toIndentedString(offlineTimeout)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    entityVersion: ").append(toIndentedString(entityVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

