/**
 * Device Hive REST API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.devicehive.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * JwtPayload
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-09T14:31:42.381+02:00")
public class JwtPayload   {
  @SerializedName("userId")
  private Long userId = null;

  @SerializedName("actions")
  private List<String> actions = new ArrayList<String>();

  @SerializedName("networkIds")
  private List<String> networkIds = new ArrayList<String>();

  @SerializedName("deviceGuids")
  private List<String> deviceGuids = new ArrayList<String>();

  public JwtPayload userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public JwtPayload actions(List<String> actions) {
    this.actions = actions;
    return this;
  }

  public JwtPayload addActionsItem(String actionsItem) {
    this.actions.add(actionsItem);
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getActions() {
    return actions;
  }

  public void setActions(List<String> actions) {
    this.actions = actions;
  }

  public JwtPayload networkIds(List<String> networkIds) {
    this.networkIds = networkIds;
    return this;
  }

  public JwtPayload addNetworkIdsItem(String networkIdsItem) {
    this.networkIds.add(networkIdsItem);
    return this;
  }

   /**
   * Get networkIds
   * @return networkIds
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getNetworkIds() {
    return networkIds;
  }

  public void setNetworkIds(List<String> networkIds) {
    this.networkIds = networkIds;
  }

  public JwtPayload deviceGuids(List<String> deviceGuids) {
    this.deviceGuids = deviceGuids;
    return this;
  }

  public JwtPayload addDeviceGuidsItem(String deviceGuidsItem) {
    this.deviceGuids.add(deviceGuidsItem);
    return this;
  }

   /**
   * Get deviceGuids
   * @return deviceGuids
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getDeviceGuids() {
    return deviceGuids;
  }

  public void setDeviceGuids(List<String> deviceGuids) {
    this.deviceGuids = deviceGuids;
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JwtPayload {\n");
    
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    networkIds: ").append(toIndentedString(networkIds)).append("\n");
    sb.append("    deviceGuids: ").append(toIndentedString(deviceGuids)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

