/*
 * Device Hive REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.3.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.devicehive.client.model;

import com.google.gson.annotations.SerializedName;
import lombok.Data;
import org.joda.time.DateTime;

import java.util.List;

/**
 * JwtPayload
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-20T15:03:42.016+03:00")
@Data
public class JwtPayload {
  @SerializedName("userId")
  private Long userId = null;

  @SerializedName("actions")
  private List<String> actions = null;

  @SerializedName("networkIds")
  private List<String> networkIds = null;

  @SerializedName("deviceIds")
  private List<String> deviceIds = null;

  @SerializedName("expiration")
  private DateTime expiration = null;

  public JwtPayload userId(Long userId) {
    this.userId = userId;
    return this;
  }
}

