/*
 * Device Hive REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.3.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.devicehive.client.model;

import com.google.gson.annotations.SerializedName;
import lombok.Data;

/**
 * UserUpdate
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-20T15:03:42.016+03:00")
@Data
public class UserUpdate {
  @SerializedName("login")
  private String login = null;

  @SerializedName("role")
  private Integer role = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("oldPassword")
  private String oldPassword = null;

  @SerializedName("data")
  private JsonStringWrapper data = null;

  @SerializedName("introReviewed")
  private Boolean introReviewed = false;

}

