/**
 * Device Hive REST API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.devicehive.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;


/**
 * UserVO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-09T14:31:42.381+02:00")
public class UserVO   {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("login")
  private String login = null;

  @SerializedName("passwordHash")
  private String passwordHash = null;

  @SerializedName("passwordSalt")
  private String passwordSalt = null;

  @SerializedName("loginAttempts")
  private Integer loginAttempts = null;

  /**
   * Gets or Sets role
   */
  public enum RoleEnum {
    @SerializedName("ADMIN")
    ADMIN("ADMIN"),
    
    @SerializedName("CLIENT")
    CLIENT("CLIENT");

    private String value;

    RoleEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("role")
  private RoleEnum role = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    @SerializedName("ACTIVE")
    ACTIVE("ACTIVE"),
    
    @SerializedName("LOCKED_OUT")
    LOCKED_OUT("LOCKED_OUT"),
    
    @SerializedName("DISABLED")
    DISABLED("DISABLED"),
    
    @SerializedName("DELETED")
    DELETED("DELETED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("lastLogin")
  private DateTime lastLogin = null;

  @SerializedName("googleLogin")
  private String googleLogin = null;

  @SerializedName("facebookLogin")
  private String facebookLogin = null;

  @SerializedName("githubLogin")
  private String githubLogin = null;

  @SerializedName("data")
  private JsonStringWrapper data = null;

  @SerializedName("admin")
  private Boolean admin = false;

  public UserVO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public UserVO login(String login) {
    this.login = login;
    return this;
  }

   /**
   * Get login
   * @return login
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getLogin() {
    return login;
  }

  public void setLogin(String login) {
    this.login = login;
  }

  public UserVO passwordHash(String passwordHash) {
    this.passwordHash = passwordHash;
    return this;
  }

   /**
   * Get passwordHash
   * @return passwordHash
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPasswordHash() {
    return passwordHash;
  }

  public void setPasswordHash(String passwordHash) {
    this.passwordHash = passwordHash;
  }

  public UserVO passwordSalt(String passwordSalt) {
    this.passwordSalt = passwordSalt;
    return this;
  }

   /**
   * Get passwordSalt
   * @return passwordSalt
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPasswordSalt() {
    return passwordSalt;
  }

  public void setPasswordSalt(String passwordSalt) {
    this.passwordSalt = passwordSalt;
  }

  public UserVO loginAttempts(Integer loginAttempts) {
    this.loginAttempts = loginAttempts;
    return this;
  }

   /**
   * Get loginAttempts
   * @return loginAttempts
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getLoginAttempts() {
    return loginAttempts;
  }

  public void setLoginAttempts(Integer loginAttempts) {
    this.loginAttempts = loginAttempts;
  }

  public UserVO role(RoleEnum role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @ApiModelProperty(example = "null", value = "")
  public RoleEnum getRole() {
    return role;
  }

  public void setRole(RoleEnum role) {
    this.role = role;
  }

  public UserVO status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public UserVO lastLogin(DateTime lastLogin) {
    this.lastLogin = lastLogin;
    return this;
  }

   /**
   * Get lastLogin
   * @return lastLogin
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getLastLogin() {
    return lastLogin;
  }

  public void setLastLogin(DateTime lastLogin) {
    this.lastLogin = lastLogin;
  }

  public UserVO googleLogin(String googleLogin) {
    this.googleLogin = googleLogin;
    return this;
  }

   /**
   * Get googleLogin
   * @return googleLogin
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGoogleLogin() {
    return googleLogin;
  }

  public void setGoogleLogin(String googleLogin) {
    this.googleLogin = googleLogin;
  }

  public UserVO facebookLogin(String facebookLogin) {
    this.facebookLogin = facebookLogin;
    return this;
  }

   /**
   * Get facebookLogin
   * @return facebookLogin
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFacebookLogin() {
    return facebookLogin;
  }

  public void setFacebookLogin(String facebookLogin) {
    this.facebookLogin = facebookLogin;
  }

  public UserVO githubLogin(String githubLogin) {
    this.githubLogin = githubLogin;
    return this;
  }

   /**
   * Get githubLogin
   * @return githubLogin
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGithubLogin() {
    return githubLogin;
  }

  public void setGithubLogin(String githubLogin) {
    this.githubLogin = githubLogin;
  }

  public UserVO data(JsonStringWrapper data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(example = "null", value = "")
  public JsonStringWrapper getData() {
    return data;
  }

  public void setData(JsonStringWrapper data) {
    this.data = data;
  }

  public UserVO admin(Boolean admin) {
    this.admin = admin;
    return this;
  }

   /**
   * Get admin
   * @return admin
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getAdmin() {
    return admin;
  }

  public void setAdmin(Boolean admin) {
    this.admin = admin;
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserVO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("    passwordHash: ").append(toIndentedString(passwordHash)).append("\n");
    sb.append("    passwordSalt: ").append(toIndentedString(passwordSalt)).append("\n");
    sb.append("    loginAttempts: ").append(toIndentedString(loginAttempts)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    lastLogin: ").append(toIndentedString(lastLogin)).append("\n");
    sb.append("    googleLogin: ").append(toIndentedString(googleLogin)).append("\n");
    sb.append("    facebookLogin: ").append(toIndentedString(facebookLogin)).append("\n");
    sb.append("    githubLogin: ").append(toIndentedString(githubLogin)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    admin: ").append(toIndentedString(admin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

