/*
 * Device Hive REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.3.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.devicehive.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * UserUpdate
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-20T15:03:42.016+03:00")
public class UserUpdate {
  @SerializedName("login")
  private String login = null;

  @SerializedName("role")
  private Integer role = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("oldPassword")
  private String oldPassword = null;

  @SerializedName("data")
  private JsonStringWrapper data = null;

  @SerializedName("introReviewed")
  private Boolean introReviewed = false;

  public UserUpdate login(String login) {
    this.login = login;
    return this;
  }

   /**
   * Get login
   * @return login
  **/
  @ApiModelProperty(value = "")
  public String getLogin() {
    return login;
  }

  public void setLogin(String login) {
    this.login = login;
  }

  public UserUpdate role(Integer role) {
    this.role = role;
    return this;
  }

   /**
   * 0 for &#39;ADMIN&#39;, 1 for &#39;CLIENT&#39;
   * minimum: 0
   * maximum: 1
   * @return role
  **/
  @ApiModelProperty(value = "0 for 'ADMIN', 1 for 'CLIENT'")
  public Integer getRole() {
    return role;
  }

  public void setRole(Integer role) {
    this.role = role;
  }

  public UserUpdate status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * 0 for &#39;ACTIVE&#39;, 1 for &#39;LOCKED_OUT&#39;, 2 for &#39;DISABLED&#39;
   * minimum: 0
   * maximum: 3
   * @return status
  **/
  @ApiModelProperty(value = "0 for 'ACTIVE', 1 for 'LOCKED_OUT', 2 for 'DISABLED'")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public UserUpdate password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @ApiModelProperty(value = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public UserUpdate oldPassword(String oldPassword) {
    this.oldPassword = oldPassword;
    return this;
  }

   /**
   * Get oldPassword
   * @return oldPassword
  **/
  @ApiModelProperty(value = "")
  public String getOldPassword() {
    return oldPassword;
  }

  public void setOldPassword(String oldPassword) {
    this.oldPassword = oldPassword;
  }

  public UserUpdate data(JsonStringWrapper data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(value = "")
  public JsonStringWrapper getData() {
    return data;
  }

  public void setData(JsonStringWrapper data) {
    this.data = data;
  }

  public UserUpdate introReviewed(Boolean introReviewed) {
    this.introReviewed = introReviewed;
    return this;
  }

   /**
   * Get introReviewed
   * @return introReviewed
  **/
  @ApiModelProperty(value = "")
  public Boolean getIntroReviewed() {
    return introReviewed;
  }

  public void setIntroReviewed(Boolean introReviewed) {
    this.introReviewed = introReviewed;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserUpdate userUpdate = (UserUpdate) o;
    return Objects.equals(this.login, userUpdate.login) &&
        Objects.equals(this.role, userUpdate.role) &&
        Objects.equals(this.status, userUpdate.status) &&
        Objects.equals(this.password, userUpdate.password) &&
        Objects.equals(this.oldPassword, userUpdate.oldPassword) &&
        Objects.equals(this.data, userUpdate.data) &&
        Objects.equals(this.introReviewed, userUpdate.introReviewed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(login, role, status, password, oldPassword, data, introReviewed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserUpdate {\n");

    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    oldPassword: ").append(toIndentedString(oldPassword)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    introReviewed: ").append(toIndentedString(introReviewed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

